### ISSUE TITLE
scanf in int=

### ISSUE THREAD

**Issue by amol31** [pchauhan13/LearnLowLevel#3]
[scanf.txt](https://github.com/pchauhan13/LearnLowLevel/files/1321848/scanf.txt)
bhai isme kya problem h

**Comment by pchauhan13** [comment]
`#include<stdio.h>
int main(){
int c;
scanf("%d\n",&c)  ;
switch(c){
case 1:
printf("one\n)");
break;
case 2 :
    printf("two\n");
    break;
case 3:
    printf("three\n");
    break;
default :
    printf("not found\n");
    }
return 0;
}
`
